name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run Infra as Code Checker
        run: |
          set -ax
          env
          SOURCE_BRANCH=${GITHUB_REF/refs\/heads\//}
          BLUBRACKET_INTEGRATION_KEY=${{ secrets.BB_API_IAC_KEY }}
          
          docker run -v ${GITHUB_WORKSPACE}:/usr/blu/iac-checker/repo \
            blubracket/iac-checker:0.0.1-beta run \
            --blubracket-service-endpoint https://nicko.blubracket.com \
            --integration-key ${BLUBRACKET_INTEGRATION_KEY} \
            --source-branch ${GITHUB_HEAD_REF:-${SOURCE_BRANCH}} \
            --target-branch ${GITHUB_BASE_REF:-""} \
            --do-not-fail-on-misconfigurations
      
